version: "3.2"
services:
  redis:
    container_name: 'delivery_hub_redis'
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD:-"HackMe"}
    ports:
     - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
     - $PWD/redis-data:/var/lib/redis
      - ./redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.28.1.4

# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
