name: Chekds
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linters
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install --upgrade pip
    - run: make install
    - run: make env
    - run: make lint

  tests:
    runs-on: ubuntu-latest
    name: Unit and integration tests
    services:
      image: redis
      options: >-
        --health-cmd "redis-cli ping"
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
      ports:
        - 6379:6379
    env:
      REDIS_PORT: 6379
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install --upgrade pip
      - run: make install
      - run: make env
      - run: make test
